import time

from app.agents.state import AgentState
from app.tools.quotation_tool import calculate_quotation_totals
from app.tools.pricing_catalog import (
    lookup_product,
    price_for_quantity,
    approved_grades,
)
from app.utils.citations import build_citation_reference
from app.core.logging import logger


def _grade_list() -> str:
    grades = sorted(g for g in approved_grades() if g)
    return ", ".join(grades) if grades else "the approved catalog grades"


def _apply_critic_revision(state: AgentState) -> None:
    """
    Apply revision instructions generated by the Critic Agent.

    The drafting agent only adds clarification questions based on
    the critic feedback. It never invents unsupported commercial
    commitments such as delivery dates, prices, or payment terms.
    """

    feedback = state.critic_feedback or {}

    if feedback.get("decision") != "revise":
        return

    issues = feedback.get("issues", [])

    for issue in issues:
        field = issue.get("field")
        customer_requirement = issue.get(
            "customer_requirement",
            ""
        )

        # -----------------------------------------------------
        # Delivery revision
        # -----------------------------------------------------
        if field == "delivery_terms":

            question = (
                "Delivery Clarification: The RFQ requests "
                f"'{customer_requirement}'. "
                "Please confirm whether this requested delivery "
                "timeline and destination can be accommodated, "
                "as the approved knowledge base does not provide "
                "sufficient evidence to guarantee this delivery "
                "commitment."
            )

            if question not in state.clarification_questions:
                state.clarification_questions.append(question)

            state.escalation_notes = (
                state.escalation_notes or ""
            )

            delivery_note = (
                " Delivery commitment requires confirmation because "
                "the requested timeline/location is not sufficiently "
                "grounded in the approved knowledge base."
            )

            if delivery_note.strip() not in state.escalation_notes:
                state.escalation_notes += delivery_note

        # -----------------------------------------------------
        # Payment revision
        # -----------------------------------------------------
        elif field == "payment_terms":

            question = (
                "Payment Terms Clarification: The RFQ requests "
                f"'{customer_requirement}'. "
                "Please confirm the requested payment terms because "
                "they cannot be issued as an approved commercial "
                "commitment without verification."
            )

            if question not in state.clarification_questions:
                state.clarification_questions.append(question)

            state.escalation_notes = (
                state.escalation_notes or ""
            )

            payment_note = (
                " Requested payment terms require verification "
                "before quotation issuance."
            )

            if payment_note.strip() not in state.escalation_notes:
                state.escalation_notes += payment_note

        # -----------------------------------------------------
        # Missing line-item revision
        # -----------------------------------------------------
        elif field == "line_items":

            question = (
                "Line Item Clarification: One or more requested "
                "line items could not be completely represented "
                "in the current quotation draft. Please confirm "
                "the missing product requirements."
            )

            if question not in state.clarification_questions:
                state.clarification_questions.append(question)


def run_drafting_agent(state: AgentState) -> AgentState:
    """
    Stage 5: Drafting Agent.

    Produces either:
    - a grounded quotation, or
    - a clarification / abstention response.

    When the Critic Agent requests revision, this agent incorporates
    the critic feedback without inventing unsupported commercial data.
    """

    start_time = time.time()

    extracted = state.extracted_requirements
    req_items = extracted.get("line_items", [])
    evidence_chunks = state.retrieved_evidence

    draft_line_items = []
    clarification_questions = list(state.clarification_questions)

    # ---------------------------------------------------------
    # Grounding / Abstention Path
    # ---------------------------------------------------------
    if state.abstention_required:

        for item in req_items:

            p_name = item.get("product_name", "")
            material = item.get("material_grade", "")
            qty = item.get("quantity", 1)

            row = lookup_product(
                item.get("product_code", ""),
                p_name
            )

            clarification_questions.append(
                f"Requirement Mismatch: Customer requested "
                f"'{material or 'unspecified'}' grade for '{p_name}'. "
                f"Approved catalogue only stocks: {_grade_list()}. "
                "Please confirm if a standard approved grade is "
                "acceptable or request a custom engineering evaluation."
            )

            draft_line_items.append({
                "product_code": (
                    f"{row['code']}-UNVERIFIED"
                    if row
                    else "UNVERIFIED"
                ),
                "product_name": (
                    f"{p_name} ({material or 'custom'} variant)"
                ),
                "material_grade": (
                    material or "unspecified"
                ),
                "quantity": qty,
                "unit_price": None,
                "total_price": None,
                "confidence_score": state.field_confidences.get(
                    p_name,
                    0.40
                ),
                "status": "abstained",
                "citations": [
                    build_citation_reference(
                        field_name="material_grade",
                        evidence_chunks=evidence_chunks,
                        default_file="product_catalog_2026.md",
                        default_snippet=(
                            "Custom alloy grades require explicit "
                            "engineering evaluation and custom pricing."
                        ),
                    )
                ],
            })

        # -----------------------------------------------------
        # Existing payment policy handling
        # -----------------------------------------------------
        if (
            extracted.get("payment_terms")
            and "90" in str(
                extracted.get("payment_terms")
            )
        ):
            clarification_questions.append(
                "Commercial Credit Policy Mismatch: Customer requested "
                "90-day credit terms. Standard company policy caps "
                "credit at Net 30 Days. Requires CFO approval."
            )

        state.clarification_questions = clarification_questions

        state.escalation_notes = (
            "AUTOMATED ABSTENTION TRIGGERED: Commercial parameters "
            "cannot be grounded in approved company knowledge base. "
            "Clarification required before formal quotation issuance."
        )

        state.quotation_draft = {
            "customer_name": state.customer_name,
            "subtotal": 0.0,
            "tax_amount": 0.0,
            "total_amount": 0.0,
            "status": "CLARIFICATION_REQUIRED",
            "line_items": draft_line_items,
        }

    # ---------------------------------------------------------
    # Grounded Path
    # ---------------------------------------------------------
    else:

        for item in req_items:

            p_name = item.get("product_name", "")
            qty = item.get("quantity", 1)

            row = lookup_product(
                item.get("product_code", ""),
                p_name
            )

            if row is None:

                draft_line_items.append({
                    "product_code": "UNVERIFIED",
                    "product_name": p_name,
                    "material_grade": item.get(
                        "material_grade",
                        ""
                    ),
                    "quantity": qty,
                    "unit_price": None,
                    "total_price": None,
                    "confidence_score": state.field_confidences.get(
                        p_name,
                        0.0
                    ),
                    "status": "unverified",
                    "citations": [],
                })

                continue

            pricing = price_for_quantity(
                row,
                qty
            )

            discount_note = (
                f" (bulk discount "
                f"{pricing['discount_rate']}% applied at qty {qty})"
                if pricing["discount_rate"]
                else ""
            )

            citation = build_citation_reference(
                field_name="unit_price",
                evidence_chunks=evidence_chunks,
                default_file=row["source"],
                default_snippet=(
                    f"{row['name']} ({row['grade']}) — "
                    f"INR {row['unit_price']}/unit"
                    f"{discount_note}"
                ),
            )

            draft_line_items.append({
                "product_code": row["code"],
                "product_name": row["name"],
                "material_grade": row["grade"],
                "quantity": qty,
                "unit_price": pricing["unit_price"],
                "total_price": pricing["total_price"],
                "confidence_score": state.field_confidences.get(
                    p_name,
                    0.96
                ),
                "status": "verified",
                "citations": [citation],
            })

        totals = calculate_quotation_totals(
            draft_line_items
        )

        state.quotation_draft = {
            "customer_name": state.customer_name,
            "subtotal": totals["subtotal"],
            "tax_amount": totals["tax_amount"],
            "total_amount": totals["total_amount"],
            "status": "PENDING_APPROVAL",
            "line_items": draft_line_items,
        }

    # ---------------------------------------------------------
    # Apply Critic Revision
    # ---------------------------------------------------------
    _apply_critic_revision(state)

    # ---------------------------------------------------------
    # Add clarification information to the draft itself
    # ---------------------------------------------------------
    if state.clarification_questions:

        state.quotation_draft[
            "clarification_questions"
        ] = list(
            dict.fromkeys(
                state.clarification_questions
            )
        )

    if state.escalation_notes:

        state.quotation_draft[
            "escalation_notes"
        ] = state.escalation_notes

    # ---------------------------------------------------------
    # Trace
    # ---------------------------------------------------------
    elapsed_ms = int(
        (time.time() - start_time) * 1000
    )

    revision_status = (
        " with critic revision applied"
        if state.critic_feedback.get("decision") == "revise"
        else ""
    )

    state.agent_traces.append({
        "agent_name": "Drafting Agent",
        "status": "SUCCESS",
        "output_summary": (
            f"Drafted quotation. "
            f"Status={state.quotation_draft.get('status')}. "
            f"Total Line Items={len(draft_line_items)}."
            f"{revision_status}"
        ),
        "execution_time_ms": elapsed_ms,
        "revision_count": state.revision_count,
    })

    logger.info(
        f"Drafting Agent completed in {elapsed_ms}ms"
    )

    return state
